"""Initial migration

Revision ID: ea1ade19e2c0
Revises: 
Create Date: 2026-01-04 11:07:16.005715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1ade19e2c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_noticias_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticias_titulo'), ['titulo'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)

    op.create_table('negocios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('es_vip', sa.Boolean(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('total_votos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negocios_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_es_vip'), ['es_vip'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_estado'), ['estado'], unique=False)
        batch_op.create_index('ix_negocios_estado_categoria', ['estado', 'categoria'], unique=False)
        batch_op.create_index('ix_negocios_estado_id', ['estado', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_latitud'), ['latitud'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_longitud'), ['longitud'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocios_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocios_updated_at'))
        batch_op.drop_index(batch_op.f('ix_negocios_owner_id'))
        batch_op.drop_index(batch_op.f('ix_negocios_nombre'))
        batch_op.drop_index(batch_op.f('ix_negocios_longitud'))
        batch_op.drop_index(batch_op.f('ix_negocios_latitud'))
        batch_op.drop_index('ix_negocios_estado_id')
        batch_op.drop_index('ix_negocios_estado_categoria')
        batch_op.drop_index(batch_op.f('ix_negocios_estado'))
        batch_op.drop_index(batch_op.f('ix_negocios_es_vip'))
        batch_op.drop_index(batch_op.f('ix_negocios_created_at'))
        batch_op.drop_index(batch_op.f('ix_negocios_categoria'))

    op.drop_table('negocios')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_created_at'))

    op.drop_table('usuarios')
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_noticias_titulo'))
        batch_op.drop_index(batch_op.f('ix_noticias_fecha'))

    op.drop_table('noticias')
    # ### end Alembic commands ###
